import type { Content } from "./types";
import { PHONE_TEL, PHONE_LABEL } from "./site";

export const de: Content = {
  nav: { services: "Leistungen", how: "Ablauf", results: "Ergebnisse", contact: "Kontakt", quote: "Angebot" },
  phone: PHONE_TEL,
  phoneLabel: PHONE_LABEL,
  badge: "Versichert & angemeldet · Festpreis-Garantie",
  hero: {
    title: "Entrümpeln. Umziehen. Entsorgen.",
    lead: "Alles aus einer Hand — schnell, sauber und zum Festpreis. Wir kommen mit unserem Mercedes Transporter zu dir und erledigen den Rest.",
    callCta: "Jetzt anrufen",
    whatsappCta: "WhatsApp schreiben",
    quoteCta: "Kostenloses Angebot",
    stats: [
      { value: "10+", label: "Jahre Erfahrung" },
      { value: "500+", label: "zufriedene Kunden" },
      { value: "Festpreis", label: "ohne Überraschungen" },
    ],
    imgAlt: "Mercedes Transporter von Clear Fix",
  },
  services: {
    kicker: "Leistungen",
    title: "Was wir für dich erledigen",
    cta: "Angebot anfragen →",
    items: [
      { value: "entruempelung", title: "Entrümpelung / Kellerentrümpelung", desc: "Keller, Dachboden, Garage oder Wohnung — wir räumen zuverlässig aus und entsorgen fachgerecht." },
      { value: "umzugshilfe", title: "Umzugshilfe", desc: "Tragen, verladen, transportieren. Wir packen an, damit dein Umzug stressfrei bleibt." },
      { value: "transporte", title: "Transporte", desc: "Möbel, Sperriges oder Einkäufe — wir bringen es sicher von A nach B." },
      { value: "reinigung", title: "Reinigung", desc: "Besenreine Übergabe inklusive. Auf Wunsch auch Grund- und Endreinigung." },
      { value: "wohnungsaufloesung", title: "Wohnungsauflösung", desc: "Komplette Haushaltsauflösung — diskret, respektvoll und vollständig." },
      { value: "sperrmuell", title: "Sperrmüll-Entsorgung", desc: "Alte Möbel und Sperrmüll fachgerecht und umweltbewusst entsorgt." },
    ],
  },
  how: {
    kicker: "So einfach geht's",
    title: "In 3 Schritten erledigt",
    steps: [
      { title: "Anfragen", desc: "Ruf an, schreib per WhatsApp oder nutze das Formular. Fotos helfen uns bei der Einschätzung." },
      { title: "Festpreis erhalten", desc: "Du bekommst ein klares Angebot zum Festpreis — kostenlos und unverbindlich." },
      { title: "Wir erledigen den Rest", desc: "Wir kommen pünktlich, arbeiten sauber und hinterlassen alles besenrein." },
    ],
  },
  results: {
    kicker: "Ergebnisse",
    title: "Vorher / Nachher",
    items: [
      { before: "Keller — vorher", after: "Keller — nachher", labelBefore: "Vorher", labelAfter: "Nachher ✓", imgBefore: "/images/basement-before.jpg", imgAfter: "/images/basement-after.jpg" },
      { before: "Wohnung — vorher", after: "Wohnung — nachher", labelBefore: "Vorher", labelAfter: "Nachher ✓", imgBefore: "/images/apartment-before.jpg", imgAfter: "/images/apartment-after.jpg" },
    ],
  },
  reviews: {
    kicker: "Kundenstimmen",
    title: "Das sagen unsere Kunden",
    items: [
      { name: "Sabine K., Berlin-Charlottenburg", text: "Kellerentrümpelung am selben Tag erledigt. Festpreis hat gestimmt, alles besenrein. Absolut empfehlenswert!" },
      { name: "Thomas R., Berlin-Pankow", text: "Schneller, freundlicher Umzug ohne Stress. Das Team war pünktlich und sehr sorgfältig." },
      { name: "Familie Weber, Potsdam", text: "Komplette Wohnungsauflösung diskret und zuverlässig. Faire Preise, klare Absprachen." },
    ],
  },
  form: {
    kicker: "Kostenloses Angebot anfragen",
    title: "Angebot anfragen",
    sub: "Unverbindlich & kostenlos — wir melden uns innerhalb von 24 Stunden.",
    name: "Name",
    email: "E-Mail",
    phone: "Telefon",
    service: "Leistung",
    message: "Nachricht",
    consent: "Mit dem Absenden stimmst du unserer Datenschutzerklärung zu.",
    submit: "Angebot anfragen",
    sending: "Wird gesendet …",
    success: "✓ Danke für deine Anfrage! Wir melden uns innerhalb von 24 Stunden bei dir.",
    error: "Etwas ist schiefgelaufen. Bitte ruf uns an oder versuche es erneut.",
    serviceOptions: [
      { value: "entruempelung", label: "Entrümpelung / Kellerentrümpelung" },
      { value: "umzugshilfe", label: "Umzugshilfe" },
      { value: "transporte", label: "Transporte" },
      { value: "reinigung", label: "Reinigung" },
      { value: "wohnungsaufloesung", label: "Wohnungsauflösung" },
      { value: "sperrmuell", label: "Sperrmüll-Entsorgung" },
      { value: "sonstiges", label: "Sonstiges" },
    ],
  },
  contact: {
    kicker: "Kontakt",
    phoneLabel: "Telefon",
    whatsappLabel: "WhatsApp",
    whatsappCta: "Nachricht senden",
    emailLabel: "E-Mail",
    email: "info@clearfix.de",
    areaLabel: "Einsatzgebiet",
    area: "Berlin & Umgebung",
    addressLabel: "Adresse",
  },
  whatsapp: {
    message: "Hallo Clear Fix, ich hätte gerne ein kostenloses Angebot für:",
    fab: "Per WhatsApp schreiben",
    optin: "Schreib uns direkt per WhatsApp — wir antworten meist innerhalb weniger Minuten.",
  },
  footer: {
    rights: "© 2026 Clear Fix · Inhaber: Laky · Berlin",
    imprint: "Impressum",
    privacy: "Datenschutz",
  },
};
