import type { Content } from "./types";
import { PHONE_TEL, PHONE_LABEL } from "./site";

export const en: Content = {
  nav: { services: "Services", how: "How it works", results: "Results", contact: "Contact", quote: "Quote" },
  phone: PHONE_TEL,
  phoneLabel: PHONE_LABEL,
  badge: "Insured & registered · Fixed-price guarantee",
  hero: {
    title: "Declutter. Move. Dispose.",
    lead: "Everything from one team — fast, clean, and at a fixed price. We come to you with our Mercedes van and handle the rest.",
    callCta: "Call now",
    whatsappCta: "Message on WhatsApp",
    quoteCta: "Free quote",
    stats: [
      { value: "10+", label: "years of experience" },
      { value: "500+", label: "happy customers" },
      { value: "Fixed price", label: "no surprises" },
    ],
    imgAlt: "Mercedes van by Clear Fix",
  },
  services: {
    kicker: "Services",
    title: "What we take care of",
    cta: "Request a quote →",
    items: [
      { value: "entruempelung", title: "Decluttering / basement clear-out", desc: "Basement, attic, garage or apartment — we clear it out reliably and dispose of everything properly." },
      { value: "umzugshilfe", title: "Moving help", desc: "Carrying, loading, transporting. We lend a hand so your move stays stress-free." },
      { value: "transporte", title: "Transport", desc: "Furniture, bulky items or purchases — we get it safely from A to B." },
      { value: "reinigung", title: "Cleaning", desc: "Broom-clean handover included. Deep and final cleaning on request." },
      { value: "wohnungsaufloesung", title: "Apartment clearance", desc: "Complete household clearance — discreet, respectful and thorough." },
      { value: "sperrmuell", title: "Bulky waste disposal", desc: "Old furniture and bulky waste disposed of properly and responsibly." },
    ],
  },
  how: {
    kicker: "How it works",
    title: "Done in 3 steps",
    steps: [
      { title: "Get in touch", desc: "Call, message us on WhatsApp, or use the form. Photos help us estimate." },
      { title: "Get a fixed price", desc: "You receive a clear fixed-price quote — free and non-binding." },
      { title: "We handle the rest", desc: "We arrive on time, work cleanly, and leave everything broom-clean." },
    ],
  },
  results: {
    kicker: "Results",
    title: "Before / After",
    items: [
      { before: "Basement — before", after: "Basement — after", labelBefore: "Before", labelAfter: "After ✓", imgBefore: "/images/basement-before.jpg", imgAfter: "/images/basement-after.jpg" },
      { before: "Apartment — before", after: "Apartment — after", labelBefore: "Before", labelAfter: "After ✓", imgBefore: "/images/apartment-before.jpg", imgAfter: "/images/apartment-after.jpg" },
    ],
  },
  reviews: {
    kicker: "Reviews",
    title: "What customers say",
    items: [
      { name: "Sabine K., Berlin-Charlottenburg", text: "Basement cleared out the same day. The fixed price held, everything broom-clean. Highly recommended!" },
      { name: "Thomas R., Berlin-Pankow", text: "Fast, friendly move without any stress. The team was on time and very careful." },
      { name: "The Weber family, Potsdam", text: "Complete apartment clearance, discreet and reliable. Fair prices, clear agreements." },
    ],
  },
  form: {
    kicker: "Request a free quote",
    title: "Request a quote",
    sub: "Free & non-binding — we'll get back to you within 24 hours.",
    name: "Name",
    email: "Email",
    phone: "Phone",
    service: "Service",
    message: "Message",
    consent: "By submitting you agree to our privacy policy.",
    submit: "Request quote",
    sending: "Sending …",
    success: "✓ Thanks for your request! We'll get back to you within 24 hours.",
    error: "Something went wrong. Please call us or try again.",
    serviceOptions: [
      { value: "entruempelung", label: "Decluttering / basement clear-out" },
      { value: "umzugshilfe", label: "Moving help" },
      { value: "transporte", label: "Transport" },
      { value: "reinigung", label: "Cleaning" },
      { value: "wohnungsaufloesung", label: "Apartment clearance" },
      { value: "sperrmuell", label: "Bulky waste disposal" },
      { value: "sonstiges", label: "Other" },
    ],
  },
  contact: {
    kicker: "Contact",
    phoneLabel: "Phone",
    whatsappLabel: "WhatsApp",
    whatsappCta: "Send a message",
    emailLabel: "Email",
    email: "info@clearfix.de",
    areaLabel: "Service area",
    area: "Berlin & surroundings",
    addressLabel: "Address",
  },
  whatsapp: {
    message: "Hi Clear Fix, I'd like a free quote for:",
    fab: "Message us on WhatsApp",
    optin: "Message us directly on WhatsApp — we usually reply within minutes.",
  },
  footer: {
    rights: "© 2026 Clear Fix · Owner: Laky · Berlin",
    imprint: "Imprint",
    privacy: "Privacy",
  },
};
